// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	DB_URL: "https://gist.githubusercontent.com/HallexCosta/07cd491e865154f5e3d73e86da6478dc/raw/skill-icons.json";
}
