compatibility_date = "2024-11-11"
main = "./src/modules/skill-icons/index.ts"
name = "skill-icons"
compatibility_flags = [ "nodejs_compat_v2" ]
workers_dev = false
routes = [
  { pattern = "skill-icons.hallexcosta.com", custom_domain = true }
]

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[observability.logs]
enabled = true