compatibility_date = "2022-05-09"
name = "skill-icons"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = false
routes = [
  { pattern = "skill-icons.hallexcosta.com", custom_domain = true }
]