compatibility_date = "2022-05-09"
main = "./src/modules/skill-icons/index.js"
name = "skill-icons"
compatibility_flags = [ "nodejs_compat_v2" ]
workers_dev = false
routes = [
  { pattern = "skill-icons.hallexcosta.com", custom_domain = true }
]

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[vars]
DB_URL = "https://gist.githubusercontent.com/HallexCosta/07cd491e865154f5e3d73e86da6478dc/raw/skill-icons.json"