compatibility_date = "2022-05-09"
main = "./index.js"
name = "skill-icons"
usage_model = 'bundled'
compatibility_flags = []
workers_dev = false
routes = [
  { pattern = "skill-icons.hallexcosta.com", custom_domain = true }
]

[build]
command = "npm run build"
cwd = "."
watch_dir = "build_watch_dir"